INSERT INTO office_features VALUES('fully-furnished, air-con, high speed Wi-Fi, pantry, restroom, near MRT');
INSERT INTO office_features VALUES('fully-furnished, air-con, high speed Wi-Fi, pantry, restroom');
INSERT INTO office_features VALUES('fully-furnished, air-con, high speed Wi-Fi, restroom, near MRT');
INSERT INTO office_features VALUES('fully-furnished, non air-con, high speed Wi-Fi, restroom, near MRT');
INSERT INTO office_features VALUES('fully-furnished, non air-con, restroom, near MRT');
INSERT INTO office_features VALUES('fully-furnished, non air-con, near MRT');
INSERT INTO office_features VALUES('fully-furnished, air-con, high speed Wi-Fi, pantry, near MRT');
INSERT INTO office_features VALUES('fully-furnished, air-con, high speed Wi-Fi, pantry, meeting room, near MRT');
INSERT INTO office_features VALUES('fully-furnished, air-con, high speed Wi-Fi, pantry, meeting room, projector, near MRT');
INSERT INTO office_features VALUES('fully-furnished, air-con, high speed Wi-Fi, pantry, meeting room, projector, CCTV Security, near MRT');
INSERT INTO office_features VALUES('unfurnished, air-con, near MRT');
INSERT INTO office_features VALUES('unfurnished, non air-con, near MRT');
INSERT INTO office_features VALUES('unfurnished, air-con');
INSERT INTO office_features VALUES('unfurnished, non air-con');
